/**
 * ============================================================================
 * /api/reports/suspended/[id] — POST (resolve → crea referto) + DELETE
 * ============================================================================
 * Resolve: una volta completata l'anagrafica del paziente, il PDF sospeso
 * viene trasformato in un referto vero (status 'pending') e il file spostato
 * nel percorso standard {patient_id}/{report_id}/{filename}. Il referto entra
 * così nella normale coda: validazione → firma → rilascio + notifica.
 *
 * Body POST: { patient_id: uuid, report_type?, category?, sample_date? }
 * DELETE: rimuove il sospeso (file + meta) senza creare un referto.
 *
 * @version 1.0.0 — 2026-08-25
 */

import { createClient } from '@supabase/supabase-js';
import { requireRole, jsonResponse } from '../../_middleware';
import { sanitizeInput, validateUuid, validateDate } from '../../../../src/lib/validators';
import type { RequestContext } from '../../../../src/lib/types';

interface Env {
  SUPABASE_URL: string;
  SUPABASE_SERVICE_KEY: string;
}

const STAFF_ROLES = ['lab_technician', 'admin', 'super_admin', 'ostetrica'] as const;
const PREFIX = '_sospesi';

function db(env: Env) {
  return createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
}

interface SuspendedMeta {
  id: string;
  file_name: string;
  storage_path: string;
  cf: string | null;
  pdf_name: string | null;
  pdf_date: string | null;
  pdf_type: string | null;
  category: string;
  reason: string;
  file_size: number;
  created_at: string;
  created_by: string | null;
}

async function loadMeta(client: ReturnType<typeof db>, id: string): Promise<SuspendedMeta | null> {
  const { data: blob, error } = await client.storage
    .from('referti')
    .download(`${PREFIX}/${id}/meta.json`);
  if (error || !blob) return null;
  try {
    return JSON.parse(await blob.text()) as SuspendedMeta;
  } catch {
    return null;
  }
}

async function removeSuspended(client: ReturnType<typeof db>, id: string, fileName: string) {
  await client.storage.from('referti').remove([
    `${PREFIX}/${id}/${fileName}`,
    `${PREFIX}/${id}/meta.json`,
  ]);
}

// ── POST /api/reports/suspended/[id] — resolve ──────────────────────────────

export async function onRequestPost(context: {
  request: Request;
  params: { id: string };
  data: { ctx: RequestContext; env: Env };
}) {
  const { request, params, data } = context;
  const { ctx, env } = data;
  const authError = requireRole(ctx, ...STAFF_ROLES);
  if (authError) return authError;

  const suspendedId = params.id;
  if (!validateUuid(suspendedId)) {
    return jsonResponse({ success: false, error: 'ID sospeso non valido.' }, 400);
  }

  let body: { patient_id?: string; report_type?: string; category?: string; sample_date?: string };
  try {
    body = await request.json();
  } catch {
    return jsonResponse({ success: false, error: 'Richiesta non valida.' }, 400);
  }

  if (!body.patient_id || !validateUuid(body.patient_id)) {
    return jsonResponse({ success: false, error: 'patient_id mancante o non valido.' }, 400);
  }

  const client = db(env);

  // ── Load suspended meta ────────────────────────────────────────────────────
  const meta = await loadMeta(client, suspendedId);
  if (!meta) {
    return jsonResponse({ success: false, error: 'Referto sospeso non trovato (già risolto?).' }, 404);
  }

  // ── Verify patient exists and is a patient ────────────────────────────────
  const { data: patient, error: pErr } = await client
    .from('users')
    .select('id, first_name, last_name, fiscal_code, role, is_active')
    .eq('id', body.patient_id)
    .is('deleted_at', null)
    .maybeSingle();

  if (pErr || !patient) {
    return jsonResponse({ success: false, error: 'Paziente non trovato.' }, 404);
  }
  if (patient.role !== 'patient') {
    return jsonResponse({ success: false, error: 'L\'utente selezionato non è un paziente.' }, 400);
  }

  // Coherence check: if the suspended PDF has a CF, it must match the patient
  if (meta.cf && patient.fiscal_code && meta.cf !== patient.fiscal_code.toUpperCase()) {
    return jsonResponse({
      success: false,
      error: `Il codice fiscale del PDF (${meta.cf}) non corrisponde al paziente selezionato (${patient.fiscal_code}). Verifica di aver scelto il paziente giusto.`,
    }, 409);
  }

  // ── Create report row (report_number auto-generated by trigger) ───────────
  const sampleDate = body.sample_date && validateDate(body.sample_date)
    ? body.sample_date
    : (meta.pdf_date || new Date().toISOString().slice(0, 10));

  const { data: report, error: rErr } = await client
    .from('reports')
    .insert({
      patient_id: patient.id,
      patient_fiscal_code: patient.fiscal_code || meta.cf,
      report_type: sanitizeInput(body.report_type, 60) || meta.pdf_type || 'altro',
      category: sanitizeInput(body.category, 40) || meta.category || 'laboratorio',
      department: 'laboratorio',
      sample_date: sampleDate,
      status: 'pending',
      uploaded_by: ctx.user!.id,
    })
    .select('id, report_number')
    .single();

  if (rErr || !report) {
    console.error('[Suspended:resolve] Report insert error:', rErr?.message);
    return jsonResponse({ success: false, error: 'Errore nella creazione del referto.' }, 500);
  }

  // ── Move file: download from _sospesi, upload to standard path ────────────
  const newPath = `${patient.id}/${report.id}/${meta.file_name}`;

  const { data: fileBlob, error: dlErr } = await client.storage
    .from('referti')
    .download(`${PREFIX}/${suspendedId}/${meta.file_name}`);

  if (dlErr || !fileBlob) {
    console.error('[Suspended:resolve] File download error:', dlErr?.message);
    await client.from('reports').delete().eq('id', report.id);
    return jsonResponse({ success: false, error: 'File PDF del sospeso non trovato.' }, 500);
  }

  const fileBuffer = await fileBlob.arrayBuffer();
  const { error: upErr } = await client.storage
    .from('referti')
    .upload(newPath, fileBuffer, { contentType: 'application/pdf', upsert: true });

  if (upErr) {
    console.error('[Suspended:resolve] File move error:', upErr.message);
    await client.from('reports').delete().eq('id', report.id);
    return jsonResponse({ success: false, error: 'Errore nello spostamento del file.' }, 500);
  }

  // ── Compute checksum + create report_files row ────────────────────────────
  const hashBuf = await crypto.subtle.digest('SHA-256', fileBuffer);
  const checksum = Array.from(new Uint8Array(hashBuf))
    .map((b) => b.toString(16).padStart(2, '0')).join('');

  const { error: fErr } = await client.from('report_files').insert({
    report_id: report.id,
    storage_path: newPath,
    storage_bucket: 'referti',
    original_name: meta.file_name,
    mime_type: 'application/pdf',
    file_size_bytes: meta.file_size || fileBuffer.byteLength,
    checksum_sha256: checksum,
    is_encrypted: false,
    is_primary: true,
    file_type: 'report_pdf',
    uploaded_by: ctx.user!.id,
  });

  if (fErr) {
    console.error('[Suspended:resolve] report_files insert error:', fErr.message);
    await client.storage.from('referti').remove([newPath]);
    await client.from('reports').delete().eq('id', report.id);
    return jsonResponse({ success: false, error: 'Errore nella registrazione del file.' }, 500);
  }

  // ── Cleanup suspended + audit ──────────────────────────────────────────────
  await removeSuspended(client, suspendedId, meta.file_name);

  await client.from('audit_log').insert({
    user_id: ctx.user!.id,
    user_role: ctx.user!.role,
    action: 'report_create',
    target_type: 'report',
    target_id: report.id,
    ip_address: ctx.ip,
    user_agent: ctx.userAgent,
    request_id: ctx.requestId,
    details: {
      report_number: report.report_number,
      from_suspended: suspendedId,
      patient_id: patient.id,
      original_reason: meta.reason,
    },
    risk_level: 'low',
  });

  return jsonResponse({
    success: true,
    data: {
      report_id: report.id,
      report_number: report.report_number,
      patient_name: `${patient.first_name} ${patient.last_name}`,
      status: 'pending',
    },
  }, 201);
}

// ── DELETE /api/reports/suspended/[id] ───────────────────────────────────────

export async function onRequestDelete(context: {
  params: { id: string };
  data: { ctx: RequestContext; env: Env };
}) {
  const { params, data } = context;
  const { ctx, env } = data;
  // Delete aperto a tutto lo staff (richiesta 2026-08-26); resta il confirm
  // lato UI e l'audit trail con risk_level medium per tracciabilità
  const authError = requireRole(ctx, ...STAFF_ROLES);
  if (authError) return authError;

  const suspendedId = params.id;
  if (!validateUuid(suspendedId)) {
    return jsonResponse({ success: false, error: 'ID sospeso non valido.' }, 400);
  }

  const client = db(env);
  const meta = await loadMeta(client, suspendedId);
  if (!meta) {
    return jsonResponse({ success: false, error: 'Referto sospeso non trovato.' }, 404);
  }

  await removeSuspended(client, suspendedId, meta.file_name);

  await client.from('audit_log').insert({
    user_id: ctx.user!.id,
    user_role: ctx.user!.role,
    action: 'file_delete',
    target_type: 'suspended_report',
    target_id: suspendedId,
    ip_address: ctx.ip,
    user_agent: ctx.userAgent,
    request_id: ctx.requestId,
    details: { file: meta.file_name, cf: meta.cf ? '***' : null, reason: meta.reason },
    risk_level: 'medium',
  });

  return jsonResponse({ success: true, data: { id: suspendedId, deleted: true } });
}
